### ISSUE TITLE
CLI Feature Request

### ISSUE THREAD

**Issue by relma2** [colinator27/dog-scepter#11]
So... I'd like to request a CLI for DogScepter before you start working on the GUI, that does what you specified in Parts 2 and 3 of the roadmap.
UTMT does not have a CLI to my knowledge, and i think it would benefit this greatly if you did

**Comment by colinator27** [comment]
I think I had that sort of thing in mind as the first "test" of the system, to make sure that it all functions properly, before making the fully-fledged UI system. So I think this is a good idea, definitely.

**Comment by colinator27** [comment]
Some basic work has now been done for a CLI. It's currently somewhat usable but not very documented, and it's lacking some abilities. I'll update it myself as I see fit, and as the project library advances to support more asset types. Currently it's suitable for modding texture-based assets, sounds, and the like (more info on the README).

**Comment by colinator27** [comment]
Will just close this now, as the CLI does now exist and will likely continue to get new features.
