### ISSUE TITLE
Ternaries in decompilation output of pre-GMS2 games

### ISSUE THREAD

**Issue by mike309game** [colinator27/dog-scepter#20]
In Undertale 1.00, in code entry gml_Script_scr_monstersetup
![image](https://user-images.githubusercontent.com/37985864/156933801-42440a89-b880-492e-8d72-a00ce86a8538.png)

**Comment by colinator27** [comment]
Should be fixed in https://github.com/colinator27/dog-scepter/commit/c476e5aa82c155b1eeb2e5ee480242ff3f0d9c7a
