### ISSUE TITLE
Have short altnernatives for dump options

### ISSUE THREAD

**Issue by Miepee** [colinator27/dog-scepter#26]
Currently `--code`, `--strings`, `--textures`, `--rooms` don't have short alternatives.
Having something like `-c`, `-s`, `-t` or `-r`  as alternatives would be great.

**Comment by colinator27** [comment]
I considered this, but there's several conflicts with single letters, so it would probably be more confusing than useful.

**Comment by Miepee** [comment]
Which conflicts for example?
Having quick access to parameters is always useful, even if they're named slightly weird.
