### ISSUE TITLE
Interpret "-" as STDOUT

### ISSUE THREAD

**Issue by Miepee** [colinator27/dog-scepter#27]
Currently, specifying `-` as the output path will cause DogScepter to interpret it as a relative location to the current directory.
It would be more comfortable, if `-` would be interpreted as STDOUT instead.

**Comment by colinator27** [comment]
What would you expect this to do?

**Comment by Miepee** [comment]
I originally thought it'd just dump everything (code, textures, rooms etc.) into STDOUT, so it could for example be piped to somewhere else.
But now that I think about it more, this doesn't really have that many uses and would likely just pollute the codebase too much. So I'll close it instead.
