### ISSUE TITLE
Interpret Enter during create-directory-question as "yes"

### ISSUE THREAD

**Issue by Miepee** [colinator27/dog-scepter#29]
The create-directory-prompt (`Directory "foobar" does not exist. Create it? (Y/n):`) has an uppercase Y and a lowercase n. This usually is used for indication what the default choice will be. As "yes" is marked as the default choice here, I expected enter to act the same way as typing "y", which it currently does not.

Alternatively, N could be uppercased instead.

**Comment by colinator27** [comment]
Probably will want it to default to N in a lot of these cases, actually, so might just go with that... but will need to check.
